project:
  type: book
  # change output-dir to "docs" to publish to gh pages
  output-dir: docs

book:
  title: "AKSDB Tools and Resources"
  author: "N.A. Jelinski"
  date: "04-March-2024"
  cover-image: "aksdb-badge-02.png"
  
  chapters:
    - index.qmd
    - part: "WOSIS-Latest Extract Tool for Alaska"
      chapters:
      - WOSIS-latest-extract-tool.qmd
     
    # - authorship-guidelines.qmd
    # - summary.qmd
    # - references.qmd
  # appendices:
    # - co-authorship-template.qmd
    # - data-use-and-sharing.qmd

# bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual


